// Code generated by Kitex v0.2.1. DO NOT EDIT.

package aggregateddiscoveryservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/ppzqh/kitex_xds_api/github.com/envoyproxy/go-control-plane/envoy/service"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler service.AggregatedDiscoveryService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
