// Code generated by Kitex v0.2.1. DO NOT EDIT.
package aggregateddiscoveryservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/ppzqh/kitex_xds_api/discoveryv3"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler discoveryv3.AggregatedDiscoveryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
